/**
* Copyright 2015 Team Astro. All rights reserved.
*/

#ifndef ASTRO_GFX_CONFIG
#define ASTRO_GFX_CONFIG

#include <astro/config.h>

#ifndef ASTRO_GFX_CONFIG_DEBUG
#define ASTRO_GFX_CONFIG_DEBUG 0
#endif

#if !defined(ASTRO_GFX_CONFIG_RENDERER_DIRECT3D9) \
	&& !defined(ASTRO_GFX_CONFIG_RENDERER_DIRECT3D11) \
	&& !defined(ASTRO_GFX_CONFIG_RENDERER_DIRECT3D12) \
	&& !defined(ASTRO_GFX_CONFIG_RENDERER_OPENGL) \
	&& !defined(ASTRO_GFX_CONFIG_RENDERER_OPENGLES) \
	&& !defined(ASTRO_GFX_CONFIG_RENDERER_VULKAN) \
	&& !defined(ASTRO_GFX_CONFIG_RENDERER_NULL)

#	ifndef ASTRO_GFX_CONFIG_RENDERER_DIRECT3D9
#		define ASTRO_GFX_CONFIG_RENDERER_DIRECT3D9 (0 \
					|| (ASTRO_PLATFORM_WINDOWS && ASTRO_PLATFORM_WINDOWS < 0x0602 /*_WIN32_WINNT_WIN8*/) \
					|| ASTRO_PLATFORM_XBOX360 \
					? 1 : 0)
#	endif // ASTRO_GFX_CONFIG_RENDERER_DIRECT3D9

#	ifndef ASTRO_GFX_CONFIG_RENDERER_DIRECT3D11
#		define ASTRO_GFX_CONFIG_RENDERER_DIRECT3D11 (0 \
					|| (ASTRO_PLATFORM_WINDOWS && ASTRO_PLATFORM_WINDOWS >= 0x0601 /*_WIN32_WINNT_WIN7*/) \
					|| ASTRO_PLATFORM_WINRT \
					? 1 : 0)
#	endif // ASTRO_GFX_CONFIG_RENDERER_DIRECT3D11

#	ifndef ASTRO_GFX_CONFIG_RENDERER_DIRECT3D12
#		define ASTRO_GFX_CONFIG_RENDERER_DIRECT3D12 (0 \
					|| (ASTRO_PLATFORM_WINDOWS && ASTRO_PLATFORM_WINDOWS >= 0x0603 /*_WIN32_WINNT_WINBLUE*/) \
					? 1 : 0)
#	endif // ASTRO_GFX_CONFIG_RENDERER_DIRECT3D12

#	ifndef ASTRO_GFX_CONFIG_RENDERER_OPENGL
#		define ASTRO_GFX_CONFIG_RENDERER_OPENGL (0 \
					|| ASTRO_PLATFORM_FREEBSD \
					|| ASTRO_PLATFORM_LINUX \
					|| ASTRO_PLATFORM_OSX \
					|| ASTRO_PLATFORM_WINDOWS \
					? 1 : 0)
#	endif // ASTRO_GFX_CONFIG_RENDERER_OPENGL

#	ifndef ASTRO_GFX_CONFIG_RENDERER_OPENGLES
#		define ASTRO_GFX_CONFIG_RENDERER_OPENGLES (0 \
					|| ASTRO_PLATFORM_ANDROID \
					|| ASTRO_PLATFORM_EMSCRIPTEN \
					|| ASTRO_PLATFORM_IOS \
					|| ASTRO_PLATFORM_NACL \
					|| ASTRO_PLATFORM_QNX \
					|| ASTRO_PLATFORM_RPI \
					? 1 : 0)
#	endif // ASTRO_GFX_CONFIG_RENDERER_OPENGLES

#	ifndef ASTRO_GFX_CONFIG_RENDERER_VULKAN
#		define ASTRO_GFX_CONFIG_RENDERER_VULKAN 0
#	endif // ASTRO_GFX_CONFIG_RENDERER_VULKAN

#	ifndef ASTRO_GFX_CONFIG_RENDERER_NULL
#		define ASTRO_GFX_CONFIG_RENDERER_NULL (!(0 \
					|| ASTRO_GFX_CONFIG_RENDERER_DIRECT3D9 \
					|| ASTRO_GFX_CONFIG_RENDERER_DIRECT3D11 \
					|| ASTRO_GFX_CONFIG_RENDERER_DIRECT3D12 \
					|| ASTRO_GFX_CONFIG_RENDERER_OPENGL \
					|| ASTRO_GFX_CONFIG_RENDERER_OPENGLES \
					? 1 : 0) )
#	endif // ASTRO_GFX_CONFIG_RENDERER_NULL
#else
#	ifndef ASTRO_GFX_CONFIG_RENDERER_DIRECT3D9
#		define ASTRO_GFX_CONFIG_RENDERER_DIRECT3D9 0
#	endif // ASTRO_GFX_CONFIG_RENDERER_DIRECT3D9

#	ifndef ASTRO_GFX_CONFIG_RENDERER_DIRECT3D11
#		define ASTRO_GFX_CONFIG_RENDERER_DIRECT3D11 0
#	endif // ASTRO_GFX_CONFIG_RENDERER_DIRECT3D11

#	ifndef ASTRO_GFX_CONFIG_RENDERER_DIRECT3D12
#		define ASTRO_GFX_CONFIG_RENDERER_DIRECT3D12 0
#	endif // ASTRO_GFX_CONFIG_RENDERER_DIRECT3D12

#	ifndef ASTRO_GFX_CONFIG_RENDERER_OPENGL
#		define ASTRO_GFX_CONFIG_RENDERER_OPENGL 0
#	endif // ASTRO_GFX_CONFIG_RENDERER_OPENGL

#	ifndef ASTRO_GFX_CONFIG_RENDERER_OPENGLES
#		define ASTRO_GFX_CONFIG_RENDERER_OPENGLES 0
#	endif // ASTRO_GFX_CONFIG_RENDERER_OPENGLES

#	ifndef ASTRO_GFX_CONFIG_RENDERER_VULKAN
#		define ASTRO_GFX_CONFIG_RENDERER_VULKAN 0
#	endif // ASTRO_GFX_CONFIG_RENDERER_VULKAN

#	ifndef ASTRO_GFX_CONFIG_RENDERER_NULL
#		define ASTRO_GFX_CONFIG_RENDERER_NULL 0
#	endif // ASTRO_GFX_CONFIG_RENDERER_NULL
#endif // !defined...

#if ASTRO_GFX_CONFIG_RENDERER_OPENGL && ASTRO_GFX_CONFIG_RENDERER_OPENGL < 21
#	undef ASTRO_GFX_CONFIG_RENDERER_OPENGL
#	define ASTRO_GFX_CONFIG_RENDERER_OPENGL 21
#endif // ASTRO_GFX_CONFIG_RENDERER_OPENGL && ASTRO_GFX_CONFIG_RENDERER_OPENGL < 21

#if ASTRO_GFX_CONFIG_RENDERER_OPENGLES && ASTRO_GFX_CONFIG_RENDERER_OPENGLES < 20
#	undef ASTRO_GFX_CONFIG_RENDERER_OPENGLES
#	define ASTRO_GFX_CONFIG_RENDERER_OPENGLES 20
#endif // ASTRO_GFX_CONFIG_RENDERER_OPENGLES && ASTRO_GFX_CONFIG_RENDERER_OPENGLES < 20

#if ASTRO_GFX_CONFIG_RENDERER_OPENGL && ASTRO_GFX_CONFIG_RENDERER_OPENGLES
#	error "Can't define both ASTRO_GFX_CONFIG_RENDERER_OPENGL and ASTRO_GFX_CONFIG_RENDERER_OPENGLES"
#endif // ASTRO_GFX_CONFIG_RENDERER_OPENGL && ASTRO_GFX_CONFIG_RENDERER_OPENGLES

/// Enable use of extensions.
#ifndef ASTRO_GFX_CONFIG_RENDERER_USE_EXTENSIONS
#	define ASTRO_GFX_CONFIG_RENDERER_USE_EXTENSIONS 1
#endif // ASTRO_GFX_CONFIG_RENDERER_USE_EXTENSIONS

/// Enable use of tinystl.
#ifndef ASTRO_GFX_CONFIG_USE_TINYSTL
#	define ASTRO_GFX_CONFIG_USE_TINYSTL 1
#endif // ASTRO_GFX_CONFIG_USE_TINYSTL

/// Enable OculusVR integration.
#ifndef ASTRO_GFX_CONFIG_USE_OVR
#	define ASTRO_GFX_CONFIG_USE_OVR 0
#endif // ASTRO_GFX_CONFIG_USE_OVR

/// Enable nVidia PerfHUD integration.
#ifndef ASTRO_GFX_CONFIG_DEBUG_PERFHUD
#	define ASTRO_GFX_CONFIG_DEBUG_PERFHUD 0
#endif // ASTRO_GFX_CONFIG_DEBUG_NVPERFHUD

/// Enable PIX markers.
#ifndef ASTRO_GFX_CONFIG_DEBUG_PIX
#	define ASTRO_GFX_CONFIG_DEBUG_PIX ASTRO_GFX_CONFIG_DEBUG
#endif // ASTRO_GFX_CONFIG_DEBUG_PIX

/// Enable DX11 object names.
#ifndef ASTRO_GFX_CONFIG_DEBUG_OBJECT_NAME
#	define ASTRO_GFX_CONFIG_DEBUG_OBJECT_NAME ASTRO_GFX_CONFIG_DEBUG
#endif // ASTRO_GFX_CONFIG_DEBUG_OBJECT_NAME

#ifndef ASTRO_GFX_CONFIG_MULTITHREADED
#	define ASTRO_GFX_CONFIG_MULTITHREADED ( (!ASTRO_GFX_CONFIG_RENDERER_NULL)&&(0 \
						|| ASTRO_PLATFORM_ANDROID \
						|| ASTRO_PLATFORM_FREEBSD \
						|| ASTRO_PLATFORM_LINUX \
						|| ASTRO_PLATFORM_IOS \
						|| ASTRO_PLATFORM_NACL \
						|| ASTRO_PLATFORM_OSX \
						|| ASTRO_PLATFORM_QNX \
						|| ASTRO_PLATFORM_RPI \
						|| ASTRO_PLATFORM_WINDOWS \
						|| ASTRO_PLATFORM_WINRT \
						|| ASTRO_PLATFORM_XBOX360 \
						? 1 : 0) )
#endif // ASTRO_GFX_CONFIG_MULTITHREADED

#ifndef ASTRO_GFX_CONFIG_MAX_DRAW_CALLS
#	define ASTRO_GFX_CONFIG_MAX_DRAW_CALLS ( (64<<10)-1)
#endif // ASTRO_GFX_CONFIG_MAX_DRAW_CALLS

#ifndef ASTRO_GFX_CONFIG_MAX_MATRIX_CACHE
#	define ASTRO_GFX_CONFIG_MAX_MATRIX_CACHE (ASTRO_GFX_CONFIG_MAX_DRAW_CALLS+1)
#endif // ASTRO_GFX_CONFIG_MAX_MATRIX_CACHE

#ifndef ASTRO_GFX_CONFIG_MAX_RECT_CACHE
#	define ASTRO_GFX_CONFIG_MAX_RECT_CACHE (4<<10)
#endif //  ASTRO_GFX_CONFIG_MAX_RECT_CACHE

#ifndef ASTRO_GFX_CONFIG_MAX_VIEWS
// Do not change. Must be power of 2.
#	define ASTRO_GFX_CONFIG_MAX_VIEWS 256
#endif // ASTRO_GFX_CONFIG_MAX_VIEWS

#define ASTRO_GFX_CONFIG_MAX_VIEW_NAME_RESERVED 6

#ifndef ASTRO_GFX_CONFIG_MAX_VIEW_NAME
#	define ASTRO_GFX_CONFIG_MAX_VIEW_NAME 256
#endif // ASTRO_GFX_CONFIG_MAX_VIEW_NAME

#ifndef ASTRO_GFX_CONFIG_MAX_VERTEX_DECLS
#	define ASTRO_GFX_CONFIG_MAX_VERTEX_DECLS 64
#endif // ASTRO_GFX_CONFIG_MAX_VERTEX_DECLS

#ifndef ASTRO_GFX_CONFIG_MAX_INDEX_BUFFERS
#	define ASTRO_GFX_CONFIG_MAX_INDEX_BUFFERS (4<<10)
#endif // ASTRO_GFX_CONFIG_MAX_INDEX_BUFFERS

#ifndef ASTRO_GFX_CONFIG_MAX_VERTEX_BUFFERS
#	define ASTRO_GFX_CONFIG_MAX_VERTEX_BUFFERS (4<<10)
#endif // ASTRO_GFX_CONFIG_MAX_VERTEX_BUFFERS

#ifndef ASTRO_GFX_CONFIG_MAX_DYNAMIC_INDEX_BUFFERS
#	define ASTRO_GFX_CONFIG_MAX_DYNAMIC_INDEX_BUFFERS (4<<10)
#endif // ASTRO_GFX_CONFIG_MAX_DYNAMIC_INDEX_BUFFERS

#ifndef ASTRO_GFX_CONFIG_MAX_DYNAMIC_VERTEX_BUFFERS
#	define ASTRO_GFX_CONFIG_MAX_DYNAMIC_VERTEX_BUFFERS (4<<10)
#endif // ASTRO_GFX_CONFIG_MAX_DYNAMIC_VERTEX_BUFFERS

#ifndef ASTRO_GFX_CONFIG_DYNAMIC_INDEX_BUFFER_SIZE
#	define ASTRO_GFX_CONFIG_DYNAMIC_INDEX_BUFFER_SIZE (1<<20)
#endif // ASTRO_GFX_CONFIG_DYNAMIC_INDEX_BUFFER_SIZE

#ifndef ASTRO_GFX_CONFIG_DYNAMIC_VERTEX_BUFFER_SIZE
#	define ASTRO_GFX_CONFIG_DYNAMIC_VERTEX_BUFFER_SIZE (3<<20)
#endif // ASTRO_GFX_CONFIG_DYNAMIC_VERTEX_BUFFER_SIZE

#ifndef ASTRO_GFX_CONFIG_MAX_SHADERS
#	define ASTRO_GFX_CONFIG_MAX_SHADERS 512
#endif // ASTRO_GFX_CONFIG_MAX_FRAGMENT_SHADERS

#ifndef ASTRO_GFX_CONFIG_MAX_PROGRAMS
// Must be power of 2.
#	define ASTRO_GFX_CONFIG_MAX_PROGRAMS 512
#endif // ASTRO_GFX_CONFIG_MAX_PROGRAMS

#ifndef ASTRO_GFX_CONFIG_MAX_TEXTURES
#	define ASTRO_GFX_CONFIG_MAX_TEXTURES (4<<10)
#endif // ASTRO_GFX_CONFIG_MAX_TEXTURES

#ifndef ASTRO_GFX_CONFIG_MAX_TEXTURE_SAMPLERS
#	define ASTRO_GFX_CONFIG_MAX_TEXTURE_SAMPLERS 16
#endif // ASTRO_GFX_CONFIG_MAX_TEXTURE_SAMPLERS

#ifndef ASTRO_GFX_CONFIG_MAX_FRAME_BUFFERS
#	define ASTRO_GFX_CONFIG_MAX_FRAME_BUFFERS 64
#endif // ASTRO_GFX_CONFIG_MAX_FRAME_BUFFERS

#ifndef ASTRO_GFX_CONFIG_MAX_FRAME_BUFFER_ATTACHMENTS
#	define ASTRO_GFX_CONFIG_MAX_FRAME_BUFFER_ATTACHMENTS 8
#endif // ASTRO_GFX_CONFIG_MAX_FRAME_BUFFER_ATTACHMENTS

#ifndef ASTRO_GFX_CONFIG_MAX_UNIFORMS
#	define ASTRO_GFX_CONFIG_MAX_UNIFORMS 512
#endif // ASTRO_GFX_CONFIG_MAX_CONSTANTS

#ifndef ASTRO_GFX_CONFIG_MAX_COMMAND_BUFFER_SIZE
#	define ASTRO_GFX_CONFIG_MAX_COMMAND_BUFFER_SIZE (64<<10)
#endif // ASTRO_GFX_CONFIG_MAX_COMMAND_BUFFER_SIZE

#ifndef ASTRO_GFX_CONFIG_TRANSIENT_VERTEX_BUFFER_SIZE
#	define ASTRO_GFX_CONFIG_TRANSIENT_VERTEX_BUFFER_SIZE (6<<20)
#endif // ASTRO_GFX_CONFIG_TRANSIENT_VERTEX_BUFFER_SIZE

#ifndef ASTRO_GFX_CONFIG_TRANSIENT_INDEX_BUFFER_SIZE
#	define ASTRO_GFX_CONFIG_TRANSIENT_INDEX_BUFFER_SIZE (2<<20)
#endif // ASTRO_GFX_CONFIG_TRANSIENT_INDEX_BUFFER_SIZE

#ifndef ASTRO_GFX_CONFIG_MAX_CONSTANT_BUFFER_SIZE
#	define ASTRO_GFX_CONFIG_MAX_CONSTANT_BUFFER_SIZE (512<<10)
#endif // ASTRO_GFX_CONFIG_MAX_CONSTANT_BUFFER_SIZE

#ifndef ASTRO_GFX_CONFIG_MAX_INSTANCE_DATA_COUNT
#	define ASTRO_GFX_CONFIG_MAX_INSTANCE_DATA_COUNT 5
#endif // ASTRO_GFX_CONFIG_MAX_INSTANCE_DATA_COUNT

#ifndef ASTRO_GFX_CONFIG_MAX_CLEAR_COLOR_PALETTE
#	define ASTRO_GFX_CONFIG_MAX_CLEAR_COLOR_PALETTE 16
#endif // ASTRO_GFX_CONFIG_MAX_CLEAR_COLOR_PALETTE

#define ASTRO_GFX_CONFIG_DRAW_INDIRECT_STRIDE 32


#endif
