/**
* Copyright 2015 Team Astro. All rights reserved.
*/

#pragma once

#include <astro/astro.h>
#include <astro/platform.h>
#include <astro/graphics/renderer.h>
#include "config.h"

#define ASTRO_GFX_RENDERER_NULL_NAME "NULL"

#if ASTRO_GFX_CONFIG_RENDERER_OPENGL
#	if ASTRO_GFX_CONFIG_RENDERER_OPENGL >= 31 && ASTRO_GFX_CONFIG_RENDERER_OPENGL <= 33
#		if ASTRO_GFX_CONFIG_RENDERER_OPENGL == 31
#			define ASTRO_GFX_RENDERER_OPENGL_NAME "OpenGL 3.1"
#		elif ASTRO_GFX_CONFIG_RENDERER_OPENGL == 32
#			define ASTRO_GFX_RENDERER_OPENGL_NAME "OpenGL 3.2"
#		else
#			define ASTRO_GFX_RENDERER_OPENGL_NAME "OpenGL 3.3"
#		endif // 31+
#	elif ASTRO_GFX_CONFIG_RENDERER_OPENGL >= 40 && ASTRO_GFX_CONFIG_RENDERER_OPENGL <= 45
#		if ASTRO_GFX_CONFIG_RENDERER_OPENGL == 40
#			define ASTRO_GFX_RENDERER_OPENGL_NAME "OpenGL 4.0"
#		elif ASTRO_GFX_CONFIG_RENDERER_OPENGL == 41
#			define ASTRO_GFX_RENDERER_OPENGL_NAME "OpenGL 4.1"
#		elif ASTRO_GFX_CONFIG_RENDERER_OPENGL == 42
#			define ASTRO_GFX_RENDERER_OPENGL_NAME "OpenGL 4.2"
#		elif ASTRO_GFX_CONFIG_RENDERER_OPENGL == 43
#			define ASTRO_GFX_RENDERER_OPENGL_NAME "OpenGL 4.3"
#		elif ASTRO_GFX_CONFIG_RENDERER_OPENGL == 44
#			define ASTRO_GFX_RENDERER_OPENGL_NAME "OpenGL 4.4"
#		else
#			define ASTRO_GFX_RENDERER_OPENGL_NAME "OpenGL 4.5"
#		endif // 40+
#	else
#		define ASTRO_GFX_RENDERER_OPENGL_NAME "OpenGL 2.1"
#	endif // ASTRO_GFX_CONFIG_RENDERER_OPENGL
#elif ASTRO_GFX_CONFIG_RENDERER_OPENGLES
#	if ASTRO_GFX_CONFIG_RENDERER_OPENGLES == 30
#		define ASTRO_GFX_RENDERER_OPENGL_NAME "OpenGL ES 3.0"
#	elif ASTRO_GFX_CONFIG_RENDERER_OPENGLES >= 31
#		define ASTRO_GFX_RENDERER_OPENGL_NAME "OpenGL ES 3.1"
#	else
#		define ASTRO_GFX_RENDERER_OPENGL_NAME "OpenGL ES 2.0"
#	endif // ASTRO_GFX_CONFIG_RENDERER_OPENGLES
#else
#	define ASTRO_GFX_RENDERER_OPENGL_NAME "OpenGL"
#endif //

namespace astro { namespace graphics
{

}
}
